### ISSUE TITLE
​开机自启不显示主界面

### ISSUE THREAD

**Issue by handsomelong922** [JasonWei512/EnergyStarX#107]
### The problem you want to solve / 你想要解决的问题

我设置了开机自启,电脑开启时他总是显示主界面,每次都需要手动关闭

### Possible solution / 可能的解决方法

能否添加一个选项,即启动软件自动最小化到右下角图标栏,而不显示主界面,谢谢您

**Comment by JasonWei512** [comment]
我没有遇到这个问题。你有没有勾选`以管理员身份开机启动`？

**Comment by handsomelong922** [comment]
> 我没有遇到这个问题。你有没有勾选`以管理员身份开机启动`？
更新了系统,好了哈哈哈,谢谢
