### ISSUE TITLE
滚动条不支持鼠标滚轮滚动​

### ISSUE THREAD

**Issue by laosanyuan** [JasonWei512/EnergyStarX#26]
### The problem you want to solve / 你想要解决的问题

当前“日志”、“帮助”等包含滚动条的页面不支持鼠标滚轮滚动翻页，只能通过鼠标拖动滑块滚动，使用起来有些不方便，是否应加入鼠标滚轮滚动页面

### Possible solution / 可能的解决方法

ScrollViewer可能需要设置

**Comment by JasonWei512** [comment]
没遇到这个问题。你有没有用什么鼠标相关的软件？关掉再试试。
https://github.com/microsoft/microsoft-ui-xaml/issues/5470
另外你按照报 bug 的 issue 模版发一下系统软硬件信息。

**Comment by laosanyuan** [comment]
> 没遇到这个问题。你有没有用什么鼠标相关的软件？关掉再试试。 [microsoft/microsoft-ui-xaml#5470](https://github.com/microsoft/microsoft-ui-xaml/issues/5470) 另外你按照报 bug 的 issue 模版发一下系统软硬件信息。

我看了这里提到的问题，排查了我本地的进程没有发现有疑似钩子操作的程序。
但是我重新创建了一个控WinUI 3的程序，验证也有相同的现象。应该是与你的程序没有关系，可能是我本地的环境有问题，但是没查到，这个issue可以关掉了。

**Comment by JasonWei512** [comment]
那我把这个 issue 关了。
WinUI 3 总是有奇奇怪怪的问题 😂
