### ISSUE TITLE
Firefox 现已支持效率模式 / Firefox now suppports efficency mode of Windows 11​

### ISSUE THREAD

**Issue by JaneValleyhasBtaken** [JasonWei512/EnergyStarX#30]
### The problem you want to solve / 你想要解决的问题

> https://www.thurrott.com/cloud/web-browsers/mozilla-firefox/276996/firefox-now-supports-windows-11s-efficiency-mode

现在Firefox也支持像Edge那样的效率模式了，这是否意味着Firefox需要像Edge那样加入到白名单中？
Now FF supports the Windows 11's efficiency mode like Edge. So, does this mean that FF should be added to the whitelist like Edge?

### Possible solution / 可能的解决方法

将Firefox加入白名单？/ Add the Firefox to the white list in the future version?

请问如果不加入又会有什么影响呢？/ What would happened if don't?

**Comment by JasonWei512** [comment]
嗯，如果程序自己适配了效率模式的话，那么最好把它加到白名单里。

浏览器每个标签页都是一个子进程，每个扩展也有自己的独立进程，还有浏览器的图像、音频进程等等。
加了白名单的话，可以让火狐自己决定哪些子进程需要标记为效率模式，更加精细。
不加白名单的话，有可能浏览器的所有子进程都会被无差别的标记为效率模式了。

**Comment by JaneValleyhasBtaken** [comment]
谢谢告知~
想请问一下未来的版本会把Firefox添加进默认的白名单吗？

**Comment by JasonWei512** [comment]
> 谢谢告知~ 想请问一下未来的版本会把Firefox添加进默认的白名单吗？（我的意思是像Edge那样；我自己是已经配置好了）

下个版本应该会加到默认白名单里（可能会要比较久，也许几周以后）。

**Comment by JasonWei512** [comment]
`1.0.4` 里火狐在默认白名单里了。
