### ISSUE TITLE
重复打开后点击“已在运行”的通知，会连续弹出新的通知 / Notifications repeat after clicking the "Already Running" message

### ISSUE THREAD

**Issue by pzm9012** [JasonWei512/EnergyStarX#34]
### Description / 描述

（也许这不是bug？）
在能源之星X已经运行的情况下，从开始屏幕打开软件，弹出“已在运行”的通知，然后点击通知气泡主体（不是关闭按钮），就会重复弹出一样内容的通知。
<img width="970" alt="屏幕截图_20230109_214437" src="https://user-images.githubusercontent.com/73187647/211327879-9ad5d244-3e43-49ab-8dd4-661434880858.png">
Open the software through the Start Screen with EnergyStarX running in background, then the "EnergyStarX is already running" message displays. After I click the notification, the same messages display repeatedly. 

### Reproduction steps / 复现步骤

1. 能源之星X在正常运行
2. 打开能源之星X
3. 点击右下角的通知

### Windows version / Windows 版本

Windows 11 22H2 Build 22621.963

### Hardware specs / 硬件配置

Huawei MateBook 14 2022
12th Gen Intel(R) Core(TM) i7-1260P   2.10 GHz
16 GB RAM  512 GB SSD

**Comment by JasonWei512** [comment]
这个不算 Bug，不过确实有点迷惑。原因是点击通知后 Windows 会尝试启动一个应用实例，结果被启动的这个应用实例发现已经有实例在运行了，所以又弹出了一个通知。

以后可能会改成 UWP 那种行为（见 #10，即：应用已打开时，再尝试启动应用会唤起已打开的应用窗口）。

This is not a bug, but yes it does look a little bit confusing. The reason for this is that Windows tries to launch an app instance when you click the notification, and then this launched app instance finds that there is already an instance running, so it shows a notification again.

I may migrate to UWP's single instance behavior in the future (see #10).

**Comment by pzm9012** [comment]
> 这个不算 Bug，不过确实有点迷惑。原因是点击通知后 Windows 会尝试启动一个应用实例，结果被启动的这个应用实例发现已经有实例在运行了，所以又弹出了一个通知。
> 
> 以后可能会改成 UWP 那种行为（见 #10，即：应用已打开时，再尝试启动应用会唤起已打开的应用窗口）。
> 
> This is not a bug, but yes it does look a little bit confusing. The reason for this is that Windows tries to launch an app instance when you click the notification, and then this launched app instance finds that there is already an instance running, so it shows a notification again.
> 
> I may migrate to UWP's single instance behavior in the future (see #10).

了解了。
***
Get it.
