### ISSUE TITLE
App crashing immediately on start up after upgrading to v1.0.5.

### ISSUE THREAD

**Issue by Winches** [JasonWei512/EnergyStarX#39]
### Description / 描述

App crashing immediately on start up after upgrading to v1.0.5(Microsoft Store).

### Reproduction steps / 复现步骤

1. Open the app.

### Windows version / Windows 版本

Windows 11 22H2 Build 22621.1194

### Hardware specs / 硬件配置

Device name ROG G14 2022
Processor AMD Ryzen 9 6900HS with Radeon Graphics 3.20 GHz
Installed RAM 40.0 GB (39.2 GB usable)

### Error log / 错误日志

Cannot view logs.

**Comment by JasonWei512** [comment]
Looks like the bug was introduced in https://github.com/JasonWei512/EnergyStarX/pull/10.
I will release a new version ASAP.

**Comment by JasonWei512** [comment]
I have submitted `v1.0.6` to Microsoft Store. 
Please upgrade to `v1.0.6`, reboot your PC, and check if the bug still occurs.

**Comment by Winches** [comment]
Thanks.It works fine.
