### ISSUE TITLE
Run as admin at startup / 以管理员身份开机自启

### ISSUE THREAD

**Issue by JasonWei512** [JasonWei512/EnergyStarX#4]
### The problem you want to solve / 你想要解决的问题

Currently Energy Star X runs without admin privileges at startup, which means it cannot throttle those programs that run with admin privileges.

目前 能源之星X 开机自启时是以非管理员权限运行的。这导致无法限制那些以管理员权限运行的程序的资源。

### Possible solution / 可能的解决方法

Register a Windows service. I am not sure whether a packaged WinUI 3 app supports this now.

注册一个 Windows 服务。我不确定一个打包 WinUI 3 应用现在支不支持这个。

**Comment by xgdgsc** [comment]
最近遇到睡眠唤醒后进程退出,是这个原因吗

**Comment by JasonWei512** [comment]
[Snipaste](https://www.microsoft.com/store/productId/9P1WXPKB68KX) implemented this by creating a schedule task in Windows Task Scheduler. However due to the limitation of MSIX package format, this schedule task won't be removed after uninstalling.

Relative issue:
https://github.com/microsoft/WindowsAppSDK/discussions/3061

**Comment by uJZk** [comment]
所以如何静默启动呢，我想手动添加到计划任务里？

**Comment by JasonWei512** [comment]
> 所以如何静默启动呢，我想手动添加到计划任务里？

创建一个以管理员身份开机时运行的计划任务，执行文件是：
C:\Users\你的用户名\AppData\Local\Microsoft\WindowsApps\EnergyStarX.exe

等以后有时间会把这个功能加入应用中。

**Comment by JasonWei512** [comment]
差不多基本做完了。需要测试个几天。
CI 编译的包：
https://github.com/JasonWei512/EnergyStarX/actions?query=branch%3Afeature%2Frun-at-startup-as-admin

**Comment by JasonWei512** [comment]
Will be shipped in `1.0.3` this weekend.
会在这周末的 `1.0.3` 版本中发布。
