### ISSUE TITLE
自带白名单加入 xray.exe​

### ISSUE THREAD

**Issue by xiaorong61** [JasonWei512/EnergyStarX#48]
### The problem you want to solve / 你想要解决的问题

xray 为代理工具 v2rayNG 所用，如果电源节流，可能会影响前台应用的网速。

### Possible solution / 可能的解决方法

自带白名单加入 xray.exe​

### Additional context / 其他信息

![image](https://user-images.githubusercontent.com/5251387/219909480-9047b22e-db37-4ad8-b37f-dd0ff44606f9.png)

**Comment by xiaorong61** [comment]
本来想直接提交 pull request 的，但没找到对应哪个文件。

**Comment by JasonWei512** [comment]
不建议加到默认白名单，因为这个默认白名单是为了满足一般大众用户的需求，要尽可能简短并且对各国家用户都有普适性。V2Ray 属于国内 + 高级用户的范畴了，所以不是很合适。
你可以自己把它加到自定义白名单里。
