### ISSUE TITLE
不好搜索​

### ISSUE THREAD

**Issue by xgdgsc** [JasonWei512/EnergyStarX#5]
### The problem you want to solve / 你想要解决的问题

在powertoys或者Windows按钮中搜索需要输入中文,,虽然windows按钮搜索理论上支持拼音,但有时候在索引或者bug搜索不到

### Possible solution / 可能的解决方法

名称添加英文,比如 "能源之星starx"

**Comment by JasonWei512** [comment]
我在 https://github.com/JasonWei512/EnergyStarX/commit/5f3d5cdf0465241850959c300561af898e92063d 里把 exe 加到 PATH 了。

你可以在搜索里输入 EnergyStarX 来启动（但是必须要打全）：

![image](https://user-images.githubusercontent.com/16899918/194246964-16910f67-36ca-418b-a62a-a14cb5399434.png)

也可以在命令行里运行 EnergyStarX 来启动：

![image](https://user-images.githubusercontent.com/16899918/194248340-b15ef2ae-6ece-4848-afa4-3ccec8c051be.png)

这个特性会包含在 0.3.7 版本里。现在还没有提交商店。想尝鲜的话可以在 [GitHub Action](https://github.com/JasonWei512/EnergyStarX/actions/runs/3195365522) 的 Artifacts 里下载 [安装包](https://github.com/JasonWei512/EnergyStarX/suites/8640752547/artifacts/388356674)。

解压后用 PowerShell 运行 Install.ps1 安装，可能要先用 PowerShell 的 `Set-ExecutionPolicy` 允许一下执行第三方脚本。

**Comment by xgdgsc** [comment]
那好像还不如输拼音快

**Comment by Mydong** [comment]
> 那好像还不如输拼音快

直接开机自启或者固定开始屏幕 很方便

**Comment by JasonWei512** [comment]
商店版的 exe 已经加到 PATH 了，在搜索或者命令行输 EnergyStarX 运行。
其他好像也没什么办法。改名暂时不考虑。或者把应用固定到开始菜单。
