### ISSUE TITLE
添加PowerToys后台组件的白名单​

### ISSUE THREAD

**Issue by yige-yigeren** [JasonWei512/EnergyStarX#51]
### The problem you want to solve / 你想要解决的问题

添加PowerToys的排除项，powertoys如果进入效率模式可能无法唤起重要组件

### Possible solution / 可能的解决方法

// PowerToys - 效率工具组件，禁用可能导致异常
PowerToys.exe
PowerToys.PowerLauncher.exe
PowerToys.KeyboardManagerEngine.exe
PowerToys.PowerOCR.exe
分别是PowerToys主进程，快速运行框，键盘重映射（效率模式可能导致此模块异常），屏幕文本识别

### Additional context / 其他信息

PowerToys是微软的一套效率工具，旨在提高windows体验
https://learn.microsoft.com/en-us/windows/powertoys/
我添加了几个重要的后台进程和子进程

**Comment by xingjunfeng** [comment]
这个你往白名单添加试试看

**Comment by yige-yigeren** [comment]
> 这个你往白名单添加试试看

加了，我这个是建议加入默认白名单

**Comment by leic4u** [comment]
@JasonWei512 PowerToys 新增 Mouse Without Borders 功能，可支持与其他 Windows 设备共享鼠标和键盘。
目前发现 EnergyStarX 会限制该功能，导致鼠标出现巨大延迟，已经几乎不可用。
尝试过将 Mouse Without Borders 功能相关的进程（包括 msedgewebview2.exe ）加入白名单，但没有起作用，应该是没有找到正确的依赖进程，请开发者帮忙看看，非常感谢。

**Comment by vinceL911** [comment]
PowerToys.KeyboardManagerEngine那个貌似是微信或其它软件劫持快捷键引起的吧。

**Comment by yige-yigeren** [comment]
> PowerToys.KeyboardManagerEngine那个貌似是微信或其它软件劫持快捷键引起的吧。

并不是，这个是powertoys的键盘重映射功能

**Comment by yige-yigeren** [comment]
> 

![image](https://github.com/JasonWei512/EnergyStarX/assets/53390868/53d885ac-30e6-4346-a625-11e99f2ccb98)

试试把PowerToys主进程加进去

**Comment by yige-yigeren** [comment]
> @JasonWei512 PowerToys 新增 Mouse Without Borders 功能，可支持与其他 Windows 设备共享鼠标和键盘。 目前发现 EnergyStarX 会限制该功能，导致鼠标出现巨大延迟，已经几乎不可用。 尝试过将 Mouse Without Borders 功能相关的进程（包括 msedgewebview2.exe ）加入白名单，但没有起作用，应该是没有找到正确的依赖进程，请开发者帮忙看看，非常感谢。

![image](https://github.com/JasonWei512/EnergyStarX/assets/53390868/f792dc50-0975-4ff1-8da6-dff00ef11d62)
试试把主进程和那个helper加进去？

**Comment by leic4u** [comment]
> > @JasonWei512 PowerToys 新增 Mouse Without Borders 功能，可支持与其他 Windows 设备共享鼠标和键盘。 目前发现 EnergyStarX 会限制该功能，导致鼠标出现巨大延迟，已经几乎不可用。 尝试过将 Mouse Without Borders 功能相关的进程（包括 msedgewebview2.exe ）加入白名单，但没有起作用，应该是没有找到正确的依赖进程，请开发者帮忙看看，非常感谢。
> 
> ![image](https://user-images.githubusercontent.com/53390868/266123843-f792dc50-0975-4ff1-8da6-dff00ef11d62.png) 试试把主进程和那个helper加进去？

不是这个问题，PowerToys v0.72 已经解决这个 bug 了，主要还是鼠标的报告率过大引起的问题，现在已经修复了。
