### ISSUE TITLE
​CPU 高占用問題

### ISSUE THREAD

**Issue by flandretw** [JasonWei512/EnergyStarX#55]
### Description / 描述

啟用背景限制後導致 CPU 高占用，且該狀況會持續發生，並增加筆電耗電（尚未確認該問題是否僅發生在 Windows Canary 和 Dev 版本中）。
<img width="496" alt="image" src="https://user-images.githubusercontent.com/51469621/225636301-db14564d-0a49-434f-8286-391b899bd3b7.png">

### Reproduction steps / 复现步骤

1. 啟用限制背景
2. 問題即發生

### Windows version / Windows 版本

Windows 11 22H2 Build 25314.1010

### Hardware specs / 硬件配置

Lenovo Legion 5 Gen6
AMD Ryzen 5600H
Nvidia RTX3050
16GB / 512GB

**Comment by JasonWei512** [comment]
我有两台 PC 用的是 Release Preview 22623.1245，还有一个 Dev Channel 25309.1000 的虚拟机，都没有遇到这个问题。

- 把网络关掉后，CPU 占用是否还这么高？
- 在 App 的主页点“暂停”按钮后，CPU 占用是否还这么高？

**Comment by flandretw** [comment]
關閉網路後占用仍然很高；使用暫停後 CPU 占用降低恢復為正常狀況。
<img width="587" alt="image" src="https://user-images.githubusercontent.com/51469621/225954942-3f835936-f2f2-4b2f-856e-0f51a9e762ee.png">
![image](https://user-images.githubusercontent.com/51469621/225955074-71c667a9-a095-4451-840c-1da5bc054320.png)

**Comment by flandretw** [comment]
重新安裝程式後問題仍然存在。

**Comment by flandretw** [comment]
2023/03/23 14:07:21.654 | INFO | Apply ProcessWhitelist:
energystar.exe
energystarx.exe
msedge.exe
webviewhost.exe
applicationframehost.exe
taskmgr.exe
procmon.exe
procmon64.exe
widgets.exe
dwm.exe
explorer.exe
shellexperiencehost.exe
startmenuexperiencehost.exe
searchhost.exe
sihost.exe
fontdrvhost.exe
chsime.exe
ctfmon.exe
csrss.exe
smss.exe
svchost.exe
wudfrd.exe
firefox.exe
2023/03/23 14:07:21.654 | INFO | Apply ProcessBlacklist:

2023/03/23 14:07:21.663 | INFO | Start throttling
2023/03/23 14:07:21.704 | INFO | House keeping task started
2023/03/23 14:07:21.704 | INFO | ThrottleStatus changed to: BlacklistAndAllButWhitelist
2023/03/23 14:07:21.711 | INFO | Power source changed to battery
2023/03/23 14:07:22.618 | INFO | Boosting PowerToys.ColorPickerUI.exe
2023/03/23 14:07:22.618 | INFO | Throttle PowerToys.ColorPickerUI.exe
2023/03/23 14:07:32.998 | INFO | Boosting PowerToys.PowerLauncher.exe
2023/03/23 14:07:33.108 | INFO | Boosting SystemSettings.exe
2023/03/23 14:07:33.108 | INFO | Throttle PowerToys.PowerLauncher.exe
2023/03/23 14:07:34.070 | INFO | Throttle SystemSettings.exe
2023/03/23 14:07:44.676 | INFO | Boosting QSHelper.exe
2023/03/23 14:07:46.995 | INFO | Boosting GoogleDriveFS.exe
2023/03/23 14:07:46.995 | INFO | Throttle QSHelper.exe
2023/03/23 14:07:47.020 | INFO | Boosting GoogleDriveFS.exe
2023/03/23 14:07:47.020 | INFO | Throttle GoogleDriveFS.exe
2023/03/23 14:07:47.837 | INFO | Throttle GoogleDriveFS.exe
2023/03/23 14:08:10.367 | INFO | Boosting vpncmgr_x64.exe
2023/03/23 14:08:13.320 | INFO | Throttle vpncmgr_x64.exe

**Comment by flandretw** [comment]
```
2023/03/23 14:07:21.654 | INFO | Apply ProcessWhitelist:
energystar.exe
energystarx.exe
msedge.exe
webviewhost.exe
applicationframehost.exe
taskmgr.exe
procmon.exe
procmon64.exe
widgets.exe
dwm.exe
explorer.exe
shellexperiencehost.exe
startmenuexperiencehost.exe
searchhost.exe
sihost.exe
fontdrvhost.exe
chsime.exe
ctfmon.exe
csrss.exe
smss.exe
svchost.exe
wudfrd.exe
firefox.exe
2023/03/23 14:07:21.654 | INFO | Apply ProcessBlacklist:

2023/03/23 14:07:21.663 | INFO | Start throttling
2023/03/23 14:07:21.704 | INFO | House keeping task started
2023/03/23 14:07:21.704 | INFO | ThrottleStatus changed to: BlacklistAndAllButWhitelist
2023/03/23 14:07:21.711 | INFO | Power source changed to battery
2023/03/23 14:07:22.618 | INFO | Boosting PowerToys.ColorPickerUI.exe
2023/03/23 14:07:22.618 | INFO | Throttle PowerToys.ColorPickerUI.exe
2023/03/23 14:07:32.998 | INFO | Boosting PowerToys.PowerLauncher.exe
2023/03/23 14:07:33.108 | INFO | Boosting SystemSettings.exe
2023/03/23 14:07:33.108 | INFO | Throttle PowerToys.PowerLauncher.exe
2023/03/23 14:07:34.070 | INFO | Throttle SystemSettings.exe
2023/03/23 14:07:44.676 | INFO | Boosting QSHelper.exe
2023/03/23 14:07:46.995 | INFO | Boosting GoogleDriveFS.exe
2023/03/23 14:07:46.995 | INFO | Throttle QSHelper.exe
2023/03/23 14:07:47.020 | INFO | Boosting GoogleDriveFS.exe
2023/03/23 14:07:47.020 | INFO | Throttle GoogleDriveFS.exe
2023/03/23 14:07:47.837 | INFO | Throttle GoogleDriveFS.exe
2023/03/23 14:08:10.367 | INFO | Boosting vpncmgr_x64.exe
2023/03/23 14:08:13.320 | INFO | Throttle vpncmgr_x64.exe

```

**Comment by flandretw** [comment]
補充擷圖（非與上次回覆時同日內容）
![image](https://user-images.githubusercontent.com/51469621/227410967-f7e3efff-3e43-4fd4-b201-7115eb1483c8.png)

**Comment by LL-LIN** [comment]
我怀疑你用了性能监控软件，之前用过一款TrafficMonitor，调用Windows的一个API导致CPU持续占用

**Comment by flandretw** [comment]
在我的印象當中沒有安裝性能監控軟件，以下是我所有的程式列表
![image](https://user-images.githubusercontent.com/51469621/227711159-d9d4c074-d9a0-4677-bc86-380d63088aa9.png)

**Comment by flandretw** [comment]
使用 GeekUninstaller 解除安裝並重新安裝解決了問題。
