### ISSUE TITLE
​能否添加设置以关闭系统托盘图标

### ISSUE THREAD

**Issue by small32** [JasonWei512/EnergyStarX#56]
### The problem you want to solve / 你想要解决的问题

如题，系统托盘图标太多了，如果能设置关闭系统托盘图标就最好了

### Possible solution / 可能的解决方法

希望能增加设置项以关闭系统托盘图标

**Comment by JasonWei512** [comment]
暂时没有这个计划。如果没有托盘图标，那么用户比较难判断应用有没有在运行，而且要关闭在后台运行的应用的话也会比较麻烦。
