### ISSUE TITLE
非常感谢作者

### ISSUE THREAD

**Issue by Mydong** [JasonWei512/EnergyStarX#6]
用上了，非常不错 16G电脑的福音；
配合内存管理工具，👩在也不用担心我的电脑卡顿了。
终于可以愉快的开启N个chrome标签页了；

感谢！

**Comment by leic4u** [comment]
@Mydong 内存管理工具是用的哪款？

**Comment by Mydong** [comment]
> @Mydong 内存管理工具是用的哪款？

mem reduct

直接搜这个  给管理员权限

**Comment by JasonWei512** [comment]
感谢你的喜欢！

**Comment by JaneValleyhasBtaken** [comment]
试了一下memreduct....确实好厉害！
