### ISSUE TITLE
​Mouse Without Borders 出现巨大延迟，几乎不可用

### ISSUE THREAD

**Issue by leic4u** [JasonWei512/EnergyStarX#71]
### Description / 描述

PowerToys v0.70.0 新增 Mouse Without Borders 功能，可支持与其他 Windows 设备共享鼠标和键盘。
目前发现 EnergyStarX 会限制该功能，导致鼠标出现巨大延迟，已经几乎不可用。
尝试过将 Mouse Without Borders 功能相关的进程（包括 msedgewebview2.exe ）加入白名单，但没有起作用，应该是没有找到正确的依赖进程，请开发者帮忙看看，非常感谢。

### Reproduction steps / 复现步骤

1. 在笔记本 A 和笔记本 B 上分别安装[ PowerToys ](https://github.com/microsoft/PowerToys/releases)；
2. 在笔记本 A 和笔记本 B 上分别开启 Mouse Without Borders 功能，并将 A B 进行链接，此时笔记本 B 的鼠标将可以控制笔记本 A ；
3. 在笔记本 A 上开启限制后台程序，此时笔记本 B 的鼠标仍可以控制笔记本 A ，但出现巨大延迟。

### Windows version / Windows 版本

Windows 11 22H2 build 22621.1778

### Hardware specs / 硬件配置

Xiaomibook Pro 15 OLED 锐龙版
AMD Ryzen 7 5800H with Radeon Graphics
16.0 GB / 512GB

**Comment by JasonWei512** [comment]
把 `PowerToys.MouseWithoutBorders.exe` 和 `PowerToys.MouseWithoutBordersHelper.exe` 添加到白名单试试。

如果你的 能源之星X 是 `v1.0.11` 及以上版本的话，把 `PowerToys*.exe` 添加到白名单，这样所有 PowerToys 进程应该就都不会被限制了。

**Comment by leic4u** [comment]
测试了下，把 `PowerToys*.exe` 加入白名单之后，也是会出现很大延迟。
所以我进行了进一步测试，发现就算关掉能源之星 X ，在笔记本断电后也会出现较大延迟。
但是在笔记本开启较少后台应用的情况下，就几乎没有延迟了。

所以应该是 MWB 适配和优化的问题，跟能源之星 X 无关。
感谢开发者答疑。
