### ISSUE TITLE
Support For Windows 21359

### ISSUE THREAD

**Issue by EntropyRiser** [JasonWei512/EnergyStarX#72]
### The problem you want to solve / 你想要解决的问题

EcoQos API has been added since 21359. But on my 21390 Windows it fails to run.
Device: Huawei Matebook E 2019, Qualcomm Snapdragon 850, Windows10 21390

### Possible solution / 可能的解决方法

I've modified the msix package's version limit but fail to install due to signature issue.

**Comment by JasonWei512** [comment]
I saw https://github.com/imbushuo/EnergyStar/issues/33. If imbushuo's EnergyStar doesn't work on 21359, this app won't work either.

**Comment by JasonWei512** [comment]
This app won't support Windows 10 21359.

But if you really want to, try [imbushuo/EnergyStar](https://github.com/imbushuo/EnergyStar) and remove these lines:

https://github.com/imbushuo/EnergyStar/blob/18872289ac4de7d22208f1fc5b156abaa904dff8/EnergyStar/Program.cs#L29-L39
