### ISSUE TITLE
The app causes lag in the mouse pointer movement 应用导致鼠标指针移动卡顿​

### ISSUE THREAD

**Issue by myfix16** [JasonWei512/EnergyStarX#73]
### Description / 描述

When the app is enabled, you can feel the obvious movement lag of the mouse pointer when you have some load on the CPU. And the issue disappears if you turn off the app. The app may throttle some tasks that are crucial to pointer movement.
当启用app的限制后台程序功能时，鼠标指针移动在CPU有负载时（例如打开IDE）出现明显卡顿。停止限制后台程序后则不会有这个问题。怀疑EnergyStarX限制了一些控制光标移动的关键进程。

### Reproduction steps / 复现步骤

1. Enable the app 
2. Start some CPU-intensive tasks (e.g., open an IDE)
3. Watch the lag happen

### Windows version / Windows 版本

Windows 11 Beta 22631.1900

### Hardware specs / 硬件配置

ASUS Zenbook 14 2023
i9-13900H
32GB + 1TB

### Error log / 错误日志

Empty `Error.txt`

**Comment by JasonWei512** [comment]
你有没有用什么鼠标相关的软件（比如 Logitech G HUB ）？
如果有的话，把它加到白名单试试。

Are you using any mouse related software (like Logitech G HUB )? 
If so, try adding it to the whitelist.

**Comment by myfix16** [comment]
The solution works. My problem is due to the `Logitech agent` and `Logitech AppBroker` being throttled. Adding them to the white list resolves the problem. I suggest EnergyStartX add relevant information to the readme file in case others have the same problem.

把罗技的`Logitech agent`和`Logitech AppBroker`进程加到白名单解决了这个问题。我建议在readme里加上对应的提示，这样别人就可以避免这个问题。

**Comment by JasonWei512** [comment]
I will add this to README.
What mouse software are you using? Logi Options+?
