### ISSUE TITLE
​Add a blackList list.

### ISSUE THREAD

**Issue by He-Pin** [JasonWei512/EnergyStarX#8]
### Description / 描述

Add a blacklist too.
Currently , we already have a whiteList, but I think a blackList should be great too.
I have a group of applications, I want to limit all of them on start.
Such as `OneAgent.exe`:)

### Reproduction steps / 复现步骤

```bash
NOOP
```

### Screenshots / 截图

```bash
NOOP
```

### Windows version / Windows 版本

win11 22h2

### Hardware specs / 硬件配置

![image](https://user-images.githubusercontent.com/501740/196220739-e2ae9a6d-d643-4439-b812-63e4202fc8c6.png)
Thinkpad p1

**Comment by JasonWei512** [comment]
I am not sure why you need a blacklist. Currently any process outside of whitelist (except programs with higher privilege like system service) will be throttled.

If you want to throttle programs with admin privileges, you can right click on the Energy Star X icon and select "Run as Admin".

If you want to throttle system services in Session 0, or run Energy Star X as admin at startup, that's not implemented yet.

Or do you want a "blacklist only" mode? That only processes on blacklist will be throttled?

**Comment by He-Pin** [comment]
Yes，i wnat to throttle all apps in the blacklist even the power adapter is connected.

**Comment by JasonWei512** [comment]
Implemented in `1.0.4`.
Note that the program you want to throttle needs to be in the same Windows session with Energy Star X.
