### ISSUE TITLE
如果以非管理员模式启动能调控管理员进程吗？

### ISSUE THREAD

**Issue by yige-yigeren** [JasonWei512/EnergyStarX#85]
同标题
因为设置管理员模式启动直接不启动了

**Comment by JasonWei512** [comment]
> 如果以非管理员模式启动能调控管理员进程吗？

不能。你可以手动以管理员身份打开应用。
![image](https://github.com/JasonWei512/EnergyStarX/assets/16899918/0a3b950e-c66d-4385-ac8b-3c81a05df8aa)

已知管理员开机自启在一小部分用户的电脑上会失效，但我找不到原因。
方便的话，你在 能源之星X 里启用 管理员开机自启，然后打开 Windows 的 `任务计划程序`，看看有没有一个叫做 `EnergyStarXAdminStartupTask` 的任务计划。
![image](https://github.com/JasonWei512/EnergyStarX/assets/16899918/62b725b7-b8b9-4257-b2b2-71b59c50a1db)

**Comment by yige-yigeren** [comment]
> 

有并且正常启动，我之前改过一下UAC不提示，现在好了
