### ISSUE TITLE
​设置页开机启动选项失效

### ISSUE THREAD

**Issue by double8fun** [JasonWei512/EnergyStarX#97]
### Description / 描述

如题，设置页开机启动选项无法打开。日志显示

> INFO | Failed to set StartupType to: User

### Reproduction steps / 复现步骤

1. 打开软件（管理员/非管理员权限均可以复现）
2. 进入设置页
3. 尝试打开开机启动开关，开关无法打开
4. 尝试在“任务管理器-启动应用”页面手动启用能源之星X，无效，关闭能源之星重启之后该页面依然显示已禁用
5. 尝试Windows商店重装无效
![20231128150240](https://github.com/JasonWei512/EnergyStarX/assets/26322217/ce94faee-1249-446b-9999-41378ca35d41)

### Windows version / Windows 版本

Windows 11 23H2 22631.2715

### Hardware specs / 硬件配置

Surface Pro 8
Intel i5 1135G7
16G / 512G

### Error log / 错误日志

2023/11/28 14:53:38.537 | INFO | Apply ProcessBlacklist:
2023/11/28 14:53:38.553 | INFO | Start throttling
2023/11/28 14:53:38.566 | INFO | House keeping task started
2023/11/28 14:53:38.566 | INFO | ThrottleStatus changed to: BlacklistAndAllButWhitelist
2023/11/28 14:53:38.566 | INFO | Power source changed to battery
2023/11/28 14:53:41.996 | INFO | Failed to set StartupType to: User

**Comment by JasonWei512** [comment]
之前有没有在任务管理器里手动禁用这个应用开机自启？
退出应用，然后在任务管理器的 `启动应用` 选项卡里右键点击这个应用启用开机自启，然后再启动应用看看。

如果不行的话，卸载应用后再安装试试。

**Comment by double8fun** [comment]
> 之前有没有在任务管理器里手动禁用这个应用开机自启？ 退出应用，然后在任务管理器的 `启动应用` 选项卡里右键点击这个应用启用开机自启，然后再启动应用看看。
> 
> 如果不行的话，卸载应用后再安装试试。

好的，我尝试一下

**Comment by double8fun** [comment]
解决了，不是app的问题，是系统的锅。
解决方案省流：保留个人文件和应用，重打了系统（乐
我发现在不开app的情况下，任务管理器`启动应用`选项卡里的设置是无效的。也就是我启用开机自启，重新打开任务管理器还是显示已禁用。后来我想起来我台式机win11的`设置-应用`里还有一个设置应用启动的页面（如图），但我发现我这个surface板子上没了，我就猜可能是之前升级23H2大版本的时候出了什么怪问题，然后重打了系统就好了。
感谢作者回复！
![image](https://github.com/JasonWei512/EnergyStarX/assets/26322217/09ec04ee-a550-456f-84d8-01747eb92fee)
